// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNPC(arg1) {
  return window['go']['main']['App']['CreateNPC'](arg1);
}

export function DeleteAllNPCs() {
  return window['go']['main']['App']['DeleteAllNPCs']();
}

export function DeleteNPC(arg1) {
  return window['go']['main']['App']['DeleteNPC'](arg1);
}

export function GenerateNPC() {
  return window['go']['main']['App']['GenerateNPC']();
}

export function GetNPC(arg1) {
  return window['go']['main']['App']['GetNPC'](arg1);
}

export function ListNPCs() {
  return window['go']['main']['App']['ListNPCs']();
}

export function SaveNPC(arg1) {
  return window['go']['main']['App']['SaveNPC'](arg1);
}
