// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNPC(arg1) {
  return window['go']['main']['WailsAPI']['CreateNPC'](arg1);
}

export function DeleteAllNPCs() {
  return window['go']['main']['WailsAPI']['DeleteAllNPCs']();
}

export function DeleteNPC(arg1) {
  return window['go']['main']['WailsAPI']['DeleteNPC'](arg1);
}

export function GenerateNPC() {
  return window['go']['main']['WailsAPI']['GenerateNPC']();
}

export function GetCreationOptions() {
  return window['go']['main']['WailsAPI']['GetCreationOptions']();
}

export function GetNPC(arg1) {
  return window['go']['main']['WailsAPI']['GetNPC'](arg1);
}

export function ListNPCs() {
  return window['go']['main']['WailsAPI']['ListNPCs']();
}

export function RollSubtypeFields(arg1) {
  return window['go']['main']['WailsAPI']['RollSubtypeFields'](arg1);
}

export function RollSpeciesName(arg1) {
  return window['go']['main']['WailsAPI']['RollSpeciesName'](arg1);
}

export function SaveNPC(arg1) {
  return window['go']['main']['WailsAPI']['SaveNPC'](arg1);
}
