// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {model} from '../models';

export function CreateNPC(arg1:main.NPCInput):Promise<model.NPC>;

export function DeleteAllNPCs():Promise<void>;

export function DeleteNPC(arg1:string):Promise<void>;

export function GenerateNPC():Promise<model.NPC>;

export function GetNPC(arg1:string):Promise<model.NPC>;

export function ListNPCs():Promise<Array<model.NPC>>;

export function SaveNPC(arg1:main.NPCInput):Promise<model.NPC>;
