// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mapper} from '../models';
import {service} from '../models';
import {main} from '../models';

export function CreateNPC(arg1:mapper.NPCInput):Promise<mapper.NPCInput>;

export function DeleteAllNPCs():Promise<void>;

export function DeleteNPC(arg1:string):Promise<void>;

export function GenerateNPC():Promise<mapper.NPCInput>;

export function GetCreationOptions():Promise<service.NPCCreationOptions>;

export function GetNPC(arg1:string):Promise<mapper.NPCInput>;

export function ListNPCs():Promise<Array<mapper.NPCInput>>;

export function RollSpeciesName(arg1:string):Promise<string>;

export function RollSubtypeFields(arg1:string):Promise<main.SubtypeRoll>;

export function SaveNPC(arg1:mapper.NPCInput):Promise<mapper.NPCInput>;
